# Generated by Django 4.2.16 on 2026-05-31 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cw_auth", "0004_carwash_user_tenant"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="stockmovement",
            new_name="inventory_s_movemen_411d79_idx",
            old_name="inventory_s_movemen_0dff9c_idx",
        ),
        migrations.RenameIndex(
            model_name="stockmovement",
            new_name="inventory_s_referen_5aaa1a_idx",
            old_name="inventory_s_referen_ef2a5e_idx",
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_items",
                to="cw_auth.carwash",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_movements",
                to="cw_auth.carwash",
            ),
        ),
    ]
