# Generated by Django 4.2.16 on 2026-06-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0002_rename_inventory_s_movemen_0dff9c_idx_inventory_s_movemen_411d79_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="sale_price_snapshot",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
