# Generated by Django 4.2.16 on 2026-06-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cw_auth", "0006_supportticket_assigned_to_supportticket_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carwash",
            name="address",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="carwash",
            name="slug",
            field=models.SlugField(blank=True, max_length=160, unique=True),
        ),
    ]
