# Generated by Django 4.2.16 on 2026-06-06 10:39

from decimal import Decimal

from django.db import migrations, models


def _response_status_score(status_value):
    mapping = {
        "closed": Decimal("5.0"),
        "answered": Decimal("4.4"),
        "pending": Decimal("3.6"),
        "open": Decimal("3.0"),
    }
    return mapping.get(status_value, Decimal("3.0"))


def _response_length_score(body):
    size = len(str(body or "").strip())
    if size >= 280:
        return Decimal("5.0")
    if size >= 160:
        return Decimal("4.6")
    if size >= 80:
        return Decimal("4.2")
    if size >= 40:
        return Decimal("3.7")
    return Decimal("2.8")


def _response_speed_score(first_response_minutes):
    minutes = float(first_response_minutes or 0)
    if minutes <= 10:
        return Decimal("5.0")
    if minutes <= 30:
        return Decimal("4.7")
    if minutes <= 60:
        return Decimal("4.2")
    if minutes <= 180:
        return Decimal("3.6")
    if minutes <= 720:
        return Decimal("3.0")
    if minutes <= 1440:
        return Decimal("2.4")
    return Decimal("1.8")


def _average_decimal(values):
    if not values:
        return Decimal("0")
    return (sum((Decimal(str(value)) for value in values), Decimal("0")) / Decimal(str(len(values)))).quantize(Decimal("0.01"))


def backfill_support_metrics(apps, schema_editor):
    User = apps.get_model("cw_auth", "User")
    SupportTicket = apps.get_model("cw_auth", "SupportTicket")

    for ticket in SupportTicket.objects.filter(responded_by__isnull=False):
        changed_fields = []
        if not ticket.assigned_to_id and ticket.responded_by_id:
            ticket.assigned_to_id = ticket.responded_by_id
            changed_fields.append("assigned_to")
        if not ticket.first_response_at and ticket.responded_at:
            ticket.first_response_at = ticket.responded_at
            changed_fields.append("first_response_at")
        if Decimal(str(ticket.response_quality_score or 0)) <= 0 and ticket.response_text:
            status_score = _response_status_score(ticket.status)
            length_score = _response_length_score(ticket.response_text)
            ticket.response_quality_score = ((status_score * Decimal("0.65")) + (length_score * Decimal("0.35"))).quantize(Decimal("0.01"))
            changed_fields.append("response_quality_score")
        if changed_fields:
            ticket.save(update_fields=changed_fields)

    for user in User.objects.filter(platform_role__in=["hq_admin", "hq_support"]):
        tickets = list(
            SupportTicket.objects.filter(assigned_to=user, responded_at__isnull=False).only(
                "status",
                "created_at",
                "first_response_at",
                "response_quality_score",
                "customer_satisfaction",
            )
        )
        satisfaction_values = [ticket.customer_satisfaction for ticket in tickets if ticket.customer_satisfaction]
        quality_values = [ticket.response_quality_score for ticket in tickets if Decimal(str(ticket.response_quality_score or 0)) > 0]
        response_minutes = []
        response_speed_values = []
        resolved_count = 0
        for ticket in tickets:
            if ticket.status == "closed":
                resolved_count += 1
            if ticket.first_response_at and ticket.created_at:
                minutes = max((ticket.first_response_at - ticket.created_at).total_seconds() / 60, 0)
                response_minutes.append(Decimal(str(round(minutes, 2))))
                response_speed_values.append(_response_speed_score(minutes))

        satisfaction_avg = _average_decimal(satisfaction_values)
        quality_avg = _average_decimal(quality_values)
        first_response_minutes_avg = _average_decimal(response_minutes)
        speed_avg = _average_decimal(response_speed_values)
        weighted_parts = []
        if satisfaction_values:
            weighted_parts.append((satisfaction_avg, Decimal("0.55")))
        if quality_values:
            weighted_parts.append((quality_avg, Decimal("0.30")))
        if response_speed_values:
            weighted_parts.append((speed_avg, Decimal("0.15")))
        if weighted_parts:
            total_weight = sum((weight for _, weight in weighted_parts), Decimal("0"))
            star_rating = (sum((value * weight for value, weight in weighted_parts), Decimal("0")) / total_weight).quantize(Decimal("0.01"))
        else:
            star_rating = Decimal("0")

        user.support_star_rating = star_rating
        user.support_rating_count = len(satisfaction_values)
        user.support_customer_satisfaction_avg = satisfaction_avg
        user.support_response_quality_avg = quality_avg
        user.support_first_response_minutes_avg = first_response_minutes_avg
        user.support_total_responses = len(tickets)
        user.support_resolved_tickets_count = resolved_count
        user.save(
            update_fields=[
                "support_star_rating",
                "support_rating_count",
                "support_customer_satisfaction_avg",
                "support_response_quality_avg",
                "support_first_response_minutes_avg",
                "support_total_responses",
                "support_resolved_tickets_count",
            ]
        )


def noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("cw_auth", "0007_carwash_address_alter_carwash_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="customer_feedback",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="customer_satisfaction",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="first_response_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="response_quality_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name="user",
            name="support_customer_satisfaction_avg",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name="user",
            name="support_first_response_minutes_avg",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="user",
            name="support_last_scored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="support_rating_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="support_resolved_tickets_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="support_response_quality_avg",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name="user",
            name="support_star_rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name="user",
            name="support_total_responses",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_support_metrics, noop),
    ]
