# Generated by Django 4.2.30 on 2026-07-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw_auth', '0015_carwash_trial_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='platform_role',
            field=models.CharField(blank=True, choices=[('', 'None'), ('hq_admin', 'HQ Admin'), ('hq_project_manager', 'HQ Project Manager'), ('hq_finance', 'HQ Finance'), ('hq_support', 'HQ Support')], default='', max_length=32),
        ),
    ]
