# Generated by Django 4.2.16 on 2026-05-31 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cw_auth", "0004_carwash_user_tenant"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notificationlog",
            new_name="notificatio_channel_7124d7_idx",
            old_name="notificatio_channel_4d5c5f_idx",
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_logs",
                to="cw_auth.carwash",
            ),
        ),
    ]
