# Generated by Codex on 2026-07-12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cw_auth', '0012_supportticket_is_registration_request_and_pendingtenantregistration'),
        ('notifications', '0003_smstemplate_customergroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('car_model', models.CharField(blank=True, max_length=120)),
                ('car_color', models.CharField(blank=True, max_length=60)),
                ('plate_number', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(default='excel', max_length=40)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_customers_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_customers', to='cw_auth.carwash')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'phone'], name='notificatio_tenant__69e9b9_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'phone'), name='uniq_imported_customer_phone_per_tenant')],
            },
        ),
    ]
