# Generated by Django 4.2.16 on 2026-05-31 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cw_auth", "0004_carwash_user_tenant"),
        ("services", "0002_generalsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsettings",
            name="tenant",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="general_settings",
                to="cw_auth.carwash",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="cw_auth.carwash",
            ),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_categories",
                to="cw_auth.carwash",
            ),
        ),
    ]
