# Generated by Django 4.2.16 on 2026-07-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0013_alter_generalsettings_sms_vehicle_released_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalsettings",
            name="sms_vehicle_assigned_template",
            field=models.TextField(
                blank=True,
                default="[نام مشتری] عزیز\nشماره پذیرش: [شماره پذیرش]\nخودروی شما با پلاک [پلاک]، در ساعت [ساعت تخصیص]، روز [تاریخ تخصیص] در مجموعه کارواش [نام کارواش] برای انجام خدمات، پذیرش شد.\n\nپیش فاکتور خدمات:\n[خلاصه خدمات]\nجمع کل: [جمع کل]\nتخفیف این سفارش: [جمع تخفیف]\nمبلغ نهایی بعد از تخفیف: [مبلغ نهایی]\nخودروی شما حدود 30 دقیقه دیگر آماده ترخیص است.\nاز اعتماد شما سپاسگزاریم.",
            ),
        ),
        migrations.AlterField(
            model_name="generalsettings",
            name="sms_vehicle_released_template",
            field=models.TextField(
                blank=True,
                default="[نام مشتری] عزیز\nخودروی شما در ساعت [ساعت ترخیص] روز [تاریخ ترخیص] از مجموعه کارواش [نام کارواش] ترخیص شد.\nامتیاز شما: [امتیاز مشتری] از ۵\nدرصد تخفیف مراجعه بعد: [درصد تخفیف مراجعه بعد]\nتعداد دفعات مراجعه: [تعداد مراجعات]\nانعام: [انعام]\nجمع تخفیف: [جمع تخفیف]\nمبلغ نهایی: [مبلغ نهایی]\nبه امید دیدار مجدد",
            ),
        ),
    ]
