# Generated by Django 4.2.16 on 2026-07-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0014_update_sms_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsettings",
            name="sms_vehicle_auto_send_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
