# Generated by Django 4.2.16 on 2026-07-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0018_alter_generalsettings_sms_vehicle_templates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalsettings",
            name="sms_vehicle_assigned_invoice_template",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="generalsettings",
            name="sms_vehicle_assigned_template",
            field=models.TextField(
                blank=True,
                default="[نام مشتری]\nخودروی شما با\nشماره پذیرش: [شماره پذیرش] با پلاک [پلاک]، در ساعت [ساعت تخصیص]، روز [تاریخ تخصیص] در مجموعه کارواش [نام کارواش] برای انجام خدمات، پذیرش شد.\nپیش فاکتور خدمات:\n[خلاصه خدمات]\nجمع کل: [جمع کل]\nتخفیف این سفارش: [جمع تخفیف]\nمبلغ نهایی بعد از تخفیف: [مبلغ نهایی]\nخودروی شما حدود 30 دقیقه دیگر آماده ترخیص است.\nاز اعتماد شما سپاسگزاریم",
            ),
        ),
    ]
