# Generated by Codex on 2026-07-19

from django.db import migrations, models


ASSIGNED_SMS_TEMPLATE = (
    "[نام مشتری]\n"
    "خودروی شما با\n"
    "شماره پذیرش: [شماره پذیرش] با پلاک [پلاک]، در ساعت [ساعت تخصیص]، روز [تاریخ تخصیص] در مجموعه کارواش [نام کارواش] "
    "برای انجام خدمات، پذیرش شد.\n"
    "خدمات:\n"
    "[خلاصه خدمات]\n"
    "---------------\n"
    "جمع کل: [جمع کل]\n"
    "تخفیف این سفارش: [جمع تخفیف]\n"
    "مبلغ نهایی: [مبلغ نهایی]\n"
    "خودروی شما حدود 30 دقیقه دیگر آماده ترخیص است.\n"
    "از اعتماد شما سپاسگزاریم"
)


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0019_alter_generalsettings_sms_vehicle_assigned_invoice_template_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalsettings",
            name="sms_vehicle_assigned_template",
            field=models.TextField(blank=True, default=ASSIGNED_SMS_TEMPLATE),
        ),
    ]
