# Generated by Django 4.2.16 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_generalsettings_discount_modes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='sms_vehicle_assigned_template',
            field=models.TextField(blank=True, default='[نام مشتری]\nخودروی شما با\nشماره پذیرش: [شماره پذیرش] با پلاک [پلاک]، در ساعت [ساعت تخصیص]، روز [تاریخ تخصیص] در مجموعه کارواش [نام کارواش] برای انجام خدمات، پذیرش شد.\nخدمات:\n[خلاصه خدمات]\n---------------\nجمع کل: [جمع کل]\nتخفیف این سفارش: [جمع تخفیف]\nمالیات: [مالیات]\nمبلغ نهایی: [مبلغ نهایی]\nخودروی شما حدود 30 دقیقه دیگر آماده ترخیص است.\nاز اعتماد شما سپاسگزاریم'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='sms_vehicle_released_template',
            field=models.TextField(blank=True, default='[نام مشتری] عزیز\nخودروی شما در ساعت [ساعت ترخیص] روز [تاریخ ترخیص] از مجموعه کارواش [نام کارواش] ترخیص شد.\nامتیاز شما: [امتیاز مشتری] از ۵\nدرصد تخفیف مراجعه بعد: [درصد تخفیف مراجعه بعد]\nتعداد دفعات مراجعه: [تعداد مراجعات]\nانعام: [انعام]\nجمع تخفیف: [جمع تخفیف]\nمالیات: [مالیات]\nمبلغ نهایی: [مبلغ نهایی]\nبه امید دیدار مجدد'),
        ),
    ]
