# Generated by Django 5.2 on 2026-05-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('cw_auth', '0001_initial'),
        ('products', '0001_initial'),
        ('services', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plate_number', models.CharField(db_index=True, max_length=20)),
                ('plate_left', models.CharField(blank=True, max_length=2)),
                ('plate_letter', models.CharField(blank=True, max_length=5)),
                ('plate_mid', models.CharField(blank=True, max_length=3)),
                ('plate_right', models.CharField(blank=True, max_length=2)),
                ('car_model', models.CharField(max_length=120)),
                ('car_color', models.CharField(max_length=60)),
                ('driver_name', models.CharField(max_length=120)),
                ('driver_phone', models.CharField(db_index=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('entered', 'Entered'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('ready_to_settle', 'Ready To Settle'), ('released', 'Released'), ('cancelled', 'Cancelled')], default='entered', max_length=30)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('intake_source', models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI'), ('hybrid', 'Hybrid')], default='manual', max_length=20)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('check_in_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_entries_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_entries_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-check_in_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker_payment_type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed')], default='percent', max_length=20)),
                ('worker_payment_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('worker_payment_fixed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('services_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('products_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('worker_share_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('carwash_share_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tip_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivered_to_worker_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_jobs', to='workers.workerprofile')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='vehicles.vehicleentry')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VehicleStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_status_changes', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='vehicles.vehicleentry')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleJobProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_job_lines', to='products.product')),
                ('vehicle_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lines', to='vehicles.vehiclejob')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleJobService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_job_lines', to='services.service')),
                ('vehicle_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_lines', to='vehicles.vehiclejob')),
            ],
        ),
        migrations.AddIndex(
            model_name='vehicleentry',
            index=models.Index(fields=['status', 'check_in_at'], name='vehicles_ve_status_8126a0_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleentry',
            index=models.Index(fields=['payment_status', 'check_in_at'], name='vehicles_ve_payment_7222c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehiclejobproduct',
            constraint=models.UniqueConstraint(fields=('vehicle_job', 'product'), name='uniq_vehicle_job_product'),
        ),
        migrations.AddConstraint(
            model_name='vehiclejobservice',
            constraint=models.UniqueConstraint(fields=('vehicle_job', 'service'), name='uniq_vehicle_job_service'),
        ),
    ]
