# Generated by Django 5.2 on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclejobservice',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
