# Generated by Django 4.2.16 on 2026-05-31 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cw_auth", "0004_carwash_user_tenant"),
        ("vehicles", "0006_vehiclejob_workers_tip_share_amount"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="vehicleentry",
            new_name="vehicles_ve_status_a92704_idx",
            old_name="vehicles_ve_status_8126a0_idx",
        ),
        migrations.RenameIndex(
            model_name="vehicleentry",
            new_name="vehicles_ve_payment_6ff5aa_idx",
            old_name="vehicles_ve_payment_7222c8_idx",
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="cw_auth.carwash",
            ),
        ),
        migrations.AddField(
            model_name="vehicleentry",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicle_entries",
                to="cw_auth.carwash",
            ),
        ),
        migrations.AddField(
            model_name="vehiclejob",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicle_jobs",
                to="cw_auth.carwash",
            ),
        ),
        migrations.AddField(
            model_name="vehiclejobproduct",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicle_job_products",
                to="cw_auth.carwash",
            ),
        ),
        migrations.AddField(
            model_name="vehiclejobservice",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicle_job_services",
                to="cw_auth.carwash",
            ),
        ),
        migrations.AddField(
            model_name="vehiclestatuslog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicle_status_logs",
                to="cw_auth.carwash",
            ),
        ),
    ]
