# Generated by Django 4.2.16 on 2026-06-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vehicles",
            "0007_rename_vehicles_ve_status_8126a0_idx_vehicles_ve_status_a92704_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclejob",
            name="manual_discount_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="vehiclejobservice",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="vehiclejob",
            name="worker_payment_type",
            field=models.CharField(
                choices=[
                    ("percent", "Percent"),
                    ("fixed", "Fixed"),
                    ("hourly", "Hourly"),
                ],
                default="percent",
                max_length=20,
            ),
        ),
    ]
