# Generated by Django 4.2.16 on 2026-06-03 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_generalsettings_tenant_service_tenant_and_more"),
        ("vehicles", "0008_vehiclejob_manual_discount_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclejobservice",
            name="custom_service_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="vehiclejobservice",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vehicle_job_lines",
                to="services.service",
            ),
        ),
    ]
