# Generated by Django 4.2.16 on 2026-06-03 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cw_auth", "0007_carwash_address_alter_carwash_slug"),
        ("vehicles", "0009_vehiclejobservice_custom_service_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedPlate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plate_number", models.CharField(db_index=True, max_length=20)),
                ("plate_left", models.CharField(blank=True, max_length=2)),
                ("plate_letter", models.CharField(blank=True, max_length=5)),
                ("plate_mid", models.CharField(blank=True, max_length=3)),
                ("plate_right", models.CharField(blank=True, max_length=2)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "blocked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blocked_vehicle_plates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_plates",
                        to="cw_auth.carwash",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="blockedplate",
            constraint=models.UniqueConstraint(
                fields=("tenant", "plate_number"), name="uniq_blocked_plate_per_tenant"
            ),
        ),
    ]
