# Generated by Django 4.2.16 on 2026-06-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0010_blockedplate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleentry",
            name="is_piece_wash",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicleentry",
            name="piece_details",
            field=models.TextField(blank=True),
        ),
    ]
