# Generated by Django 4.2.16 on 2026-07-16 23:06

from collections import defaultdict

from django.db import migrations, models
from django.utils import timezone


def backfill_admission_numbers(apps, schema_editor):
    VehicleEntry = apps.get_model("vehicles", "VehicleEntry")
    grouped_entries = defaultdict(list)
    entries = VehicleEntry.objects.order_by("tenant_id", "check_in_at", "id").only(
        "id",
        "tenant_id",
        "check_in_at",
        "admission_number",
    )
    for entry in entries:
        if entry.admission_number:
            continue
        local_date = timezone.localtime(entry.check_in_at).date() if entry.check_in_at else None
        grouped_entries[(entry.tenant_id, local_date)].append(entry)

    updates = []
    for group in grouped_entries.values():
        for offset, entry in enumerate(group):
            entry.admission_number = 1000 + offset
            updates.append(entry)

    if updates:
        VehicleEntry.objects.bulk_update(updates, ["admission_number"])


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0017_vehicleentry_sms_notifications_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleentry",
            name="admission_number",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_admission_numbers, migrations.RunPython.noop),
    ]
