# Generated by Django 4.2.30 on 2026-07-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0019_vehiclejob_apply_loyalty_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleentry',
            name='tariff_type',
            field=models.CharField(choices=[('type_1', 'Type 1'), ('type_2', 'Type 2'), ('type_3', 'Type 3'), ('type_4', 'Type 4'), ('type_5', 'Type 5'), ('type_6', 'Type 6')], default='type_1', max_length=20),
        ),
    ]
