# Generated by Django 4.2.16 on 2026-08-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0021_vehicleentry_loyalty_snapshots"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="vehicleentry",
            index=models.Index(
                fields=["tenant", "check_in_at"], name="vehicles_ve_tenant_ci_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicleentry",
            index=models.Index(
                fields=["tenant", "status", "check_in_at"],
                name="vehicles_ve_tenant_st_ci_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicleentry",
            index=models.Index(
                fields=["tenant", "plate_number"], name="vehicles_ve_tenant_plate_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehiclestatuslog",
            index=models.Index(
                fields=["vehicle", "changed_at"], name="vehicles_vsl_vehicle_ca_idx"
            ),
        ),
    ]
