# Generated by Django 4.2.16 on 2026-09-12 09:11

from django.db import migrations, models
from django.utils import timezone


OPEN_STATUSES = {'entered', 'assigned', 'in_progress', 'ready_to_settle'}


def _worker_ids_from_job(job):
    ordered = []
    snapshot = job.assigned_workers_snapshot if isinstance(job.assigned_workers_snapshot, list) else []
    for item in snapshot:
        raw = item.get('id') if isinstance(item, dict) else item
        try:
            worker_id = int(raw)
        except (TypeError, ValueError):
            continue
        if worker_id > 0 and worker_id not in ordered:
            ordered.append(worker_id)
    if job.assigned_worker_id and int(job.assigned_worker_id) not in ordered:
        ordered.insert(0, int(job.assigned_worker_id))
    return ordered


def _load_status(count):
    if count <= 0:
        return 'free'
    if count == 1:
        return 'normal'
    return 'busy'


def forwards_hold_open_jobs(apps, schema_editor):
    VehicleJob = apps.get_model('vehicles', 'VehicleJob')
    WorkerProfile = apps.get_model('workers', 'WorkerProfile')
    now = timezone.now()

    held_counts = {}
    for job in VehicleJob.objects.select_related('vehicle').iterator():
        vehicle = getattr(job, 'vehicle', None)
        if not vehicle or vehicle.status not in OPEN_STATUSES:
            continue
        worker_ids = _worker_ids_from_job(job)
        if not worker_ids:
            continue
        VehicleJob.objects.filter(pk=job.pk).update(
            workers_held=True,
            workers_freed_at=None,
            updated_at=now,
        )
        for worker_id in worker_ids:
            held_counts[worker_id] = held_counts.get(worker_id, 0) + 1

    for worker in WorkerProfile.objects.all().iterator():
        count = int(held_counts.get(worker.id, 0))
        WorkerProfile.objects.filter(pk=worker.pk).update(
            active_jobs_count=count,
            load_status=_load_status(count),
            updated_at=now,
        )


def backwards_clear_holds(apps, schema_editor):
    VehicleJob = apps.get_model('vehicles', 'VehicleJob')
    WorkerProfile = apps.get_model('workers', 'WorkerProfile')
    now = timezone.now()
    VehicleJob.objects.filter(workers_held=True).update(
        workers_held=False,
        workers_freed_at=now,
        updated_at=now,
    )
    WorkerProfile.objects.all().update(
        active_jobs_count=0,
        load_status='free',
        updated_at=now,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0022_vehicleentry_vehicles_ve_tenant_ci_idx_and_more"),
        ("workers", "0009_workerprofile_soft_delete_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclejob",
            name="workers_freed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehiclejob",
            name="workers_held",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(forwards_hold_open_jobs, backwards_clear_holds),
    ]
