# Generated by Django 5.2 on 2026-05-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('cw_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('overall', 'Overall'), ('carwash_share', 'Carwash Share'), ('worker_share', 'Worker Share'), ('tips', 'Tips'), ('attendance', 'Attendance')], max_length=40)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('summary_data', models.JSONField(blank=True, default=dict)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_snapshots_generated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='reportsnapshot',
            index=models.Index(fields=['report_type', 'period_start', 'period_end'], name='reports_rep_report__f7a2f9_idx'),
        ),
    ]
