# Generated by Django 4.2.16 on 2026-05-31 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cw_auth", "0004_carwash_user_tenant"),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="reportsnapshot",
            new_name="reports_rep_report__eaa6d4_idx",
            old_name="reports_rep_report__f7a2f9_idx",
        ),
        migrations.AddField(
            model_name="reportsnapshot",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_snapshots",
                to="cw_auth.carwash",
            ),
        ),
    ]
