# Generated by Django 4.2.16 on 2026-06-03 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cw_auth", "0007_carwash_address_alter_carwash_slug"),
        ("vehicles", "0008_vehiclejob_manual_discount_total_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workers", "0004_workerprofile_default_hourly_wage_and_more"),
        (
            "reports",
            "0002_rename_reports_rep_report__f7a2f9_idx_reports_rep_report__eaa6d4_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerPayoutTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("wage_payment", "Wage Payment"),
                            ("tip_payment", "Tip Payment"),
                            ("bonus", "Bonus"),
                            ("penalty", "Penalty"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="worker_payout_transactions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker_payout_transactions",
                        to="cw_auth.carwash",
                    ),
                ),
                (
                    "vehicle_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="worker_payout_transactions",
                        to="vehicles.vehiclejob",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_transactions",
                        to="workers.workerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["worker", "kind", "created_at"],
                        name="reports_wor_worker__0ca965_idx",
                    ),
                    models.Index(
                        fields=["tenant", "created_at"],
                        name="reports_wor_tenant__f70663_idx",
                    ),
                ],
            },
        ),
    ]
