# Generated by Django 5.2 on 2026-05-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('cw_auth', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('wallet_type', models.CharField(choices=[('cash', 'Cash'), ('pos', 'POS'), ('bank', 'Bank')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('pos', 'POS'), ('cash', 'Cash'), ('transfer', 'Transfer'), ('manual', 'Manual')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tip_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('product_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pos_reference', models.CharField(blank=True, max_length=100)),
                ('rrn', models.CharField(blank=True, max_length=60)),
                ('gateway_payload', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created', to=settings.AUTH_USER_MODEL)),
                ('vehicle_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='vehicles.vehicleentry')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashflowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference_type', models.CharField(blank=True, max_length=40)),
                ('reference_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('transacted_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashflow_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashflow_transactions', to='payments.wallet')),
            ],
            options={
                'ordering': ['-transacted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'method', 'created_at'], name='payments_pa_status_8ff6fb_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflowtransaction',
            index=models.Index(fields=['wallet', 'transacted_at'], name='payments_ca_wallet__5f5f31_idx'),
        ),
    ]
