# Generated by Django 4.2.16 on 2026-05-31 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cw_auth", "0004_carwash_user_tenant"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="cashflowtransaction",
            new_name="payments_ca_wallet__5fe31a_idx",
            old_name="payments_ca_wallet__5f5f31_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="payments_pa_status_edb130_idx",
            old_name="payments_pa_status_8ff6fb_idx",
        ),
        migrations.AddField(
            model_name="cashflowtransaction",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cashflow_transactions",
                to="cw_auth.carwash",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="cw_auth.carwash",
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallets",
                to="cw_auth.carwash",
            ),
        ),
    ]
