# Generated by Django 4.2.16 on 2026-06-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0002_rename_payments_ca_wallet__5f5f31_idx_payments_ca_wallet__5fe31a_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="wallet_type",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("pos", "POS"),
                    ("bank", "Bank"),
                    ("sms", "SMS"),
                ],
                max_length=20,
            ),
        ),
    ]
