# Generated by Django 4.2.16 on 2026-06-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_wallet_wallet_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="cheque_bank",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="payment",
            name="cheque_number",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="payment",
            name="payer_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="payment",
            name="payer_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="payment",
            name="reminder_due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("pos", "POS"),
                    ("cash", "Cash"),
                    ("transfer", "Transfer"),
                    ("cheque", "Cheque"),
                    ("credit", "Credit"),
                    ("manual", "Manual"),
                ],
                max_length=20,
            ),
        ),
    ]
